# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: RIFT bits
email: jana4u@seznam.cz
description: > # this means to ignore newlines until "baseurl:"
  Various RIFT related tips and tricks.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://rift.jana4u.net" # the base hostname & protocol for your site
twitter_username: jana4u
github_username:  jana4u

# Build settings
markdown: kramdown
